name: Postman CI - api-login

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Verificar versão do Newman e Node.js
    - name: Check version Newman and Node
      run: |
        newman --version
        node --version

    # Instalar newman-reporter-htmlextra
    - name: Install Newman-Reporter-HtmlExtra
      run: |
        sudo npm install -g newman-reporter-htmlextra

    # Executar a coleção com ambiente especificado
    - name: Execute collection
      run: |
      
        newman run 2_login/2_login.json -e 2_login/postman.env.json -g 2_login/global.json --reporters cli,htmlextra --reporter-htmlextra-export 2_login/docs/index.html



    # Carregar relatório de teste
    - name: Upload Test Report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: 2_login/docs/index.html
